import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: {
          canvas: "var(--surface-canvas)",
          elevated: "var(--surface-elevated)",
          muted: "var(--surface-muted)",
          sunken: "var(--surface-sunken)",
        },
        ink: {
          primary: "var(--ink-primary)",
          secondary: "var(--ink-secondary)",
          tertiary: "var(--ink-tertiary)",
          quaternary: "var(--ink-quaternary)",
        },
        accent: {
          DEFAULT: "var(--accent-primary)",
          hover: "var(--accent-hover)",
          muted: "var(--accent-muted)",
          glow: "var(--accent-glow)",
        },
        gold: {
          DEFAULT: "var(--gold)",
          light: "var(--gold-light)",
          muted: "var(--gold-muted)",
        },
        coral: {
          DEFAULT: "var(--coral)",
          light: "var(--coral-light)",
          muted: "var(--coral-muted)",
        },
        danger: "var(--danger)",
        warning: "var(--warning)",
        success: "var(--success)",
        info: "var(--info)",
        border: {
          light: "var(--border-light)",
          DEFAULT: "var(--border-default)",
          strong: "var(--border-strong)",
        },
        // Apple Glass (app pages)
        glass: {
          DEFAULT: "var(--glass-bg)",
          strong: "var(--glass-bg-strong)",
          subtle: "var(--glass-bg-subtle)",
          border: "var(--glass-border)",
        },
        gray: {
          50: "var(--gray-50)",
          100: "var(--gray-100)",
          200: "var(--gray-200)",
          300: "var(--gray-300)",
          400: "var(--gray-400)",
          500: "var(--gray-500)",
          600: "var(--gray-600)",
          700: "var(--gray-700)",
          900: "var(--gray-900)",
        },
        azure: {
          DEFAULT: "var(--azure)",
          hover: "var(--azure-hover)",
          muted: "var(--azure-muted)",
        },
        coralWarn: {
          DEFAULT: "var(--coral-warn)",
          muted: "var(--coral-warn-muted)",
        },
        amberCaution: {
          DEFAULT: "var(--amber-caution)",
          muted: "var(--amber-caution-muted)",
        },
        mintOk: {
          DEFAULT: "var(--mint-ok)",
          muted: "var(--mint-ok-muted)",
        },
      },
      spacing: {
        "18": "72px",
        "22": "88px",
        "26": "104px",
        "30": "120px",
        "34": "136px",
        "38": "152px",
        "42": "168px",
        "46": "184px",
        "50": "200px",
      },
      borderRadius: {
        sm: "6px",
        md: "10px",
        lg: "14px",
        xl: "20px",
        "2xl": "28px",
        "3xl": "36px",
      },
      boxShadow: {
        xs: "0 1px 2px rgba(0, 0, 0, 0.04)",
        sm: "0 2px 8px rgba(0, 0, 0, 0.06), 0 1px 2px rgba(0, 0, 0, 0.04)",
        md: "0 4px 16px rgba(0, 0, 0, 0.08), 0 2px 4px rgba(0, 0, 0, 0.04)",
        lg: "0 12px 36px rgba(0, 0, 0, 0.12), 0 4px 12px rgba(0, 0, 0, 0.08)",
        xl: "0 24px 64px rgba(0, 0, 0, 0.16), 0 8px 24px rgba(0, 0, 0, 0.10)",
        gold: "0 6px 32px rgba(255, 107, 53, 0.22)",
        coral: "0 6px 32px rgba(255, 107, 53, 0.25)",
        accent: "0 6px 32px rgba(255, 107, 53, 0.20)",
        azure: "0 6px 32px rgba(255, 107, 53, 0.25)",
        "3d-deep": "0 32px 80px -12px rgba(0, 0, 0, 0.18), 0 12px 32px -8px rgba(0, 0, 0, 0.10)",
        glass: "var(--glass-shadow)",
        "glass-lg": "0 16px 48px rgba(0, 0, 0, 0.08), 0 2px 4px rgba(0, 0, 0, 0.04)",
      },
      fontFamily: {
        display: ['"Fraunces"', '"Noto Serif SC"', "Georgia", "serif"],
        sans: ['"DM Sans"', '"PingFang SC"', '"Noto Sans SC"', '"Microsoft YaHei"', "system-ui", "sans-serif"],
        mono: ['"JetBrains Mono"', '"Menlo"', "monospace"],
        appleDisplay: ['"Inter Display"', '"Inter"', '"PingFang SC"', '"Noto Sans SC"', "system-ui", "sans-serif"],
        apple: ['"Inter"', '"PingFang SC"', '"Noto Sans SC"', "system-ui", "sans-serif"],
      },
      fontSize: {
        display: ["clamp(56px, 7vw, 96px)", { lineHeight: "1.02", fontWeight: "600", letterSpacing: "-0.035em" }],
        h1: ["clamp(40px, 4.5vw, 56px)", { lineHeight: "1.08", fontWeight: "600", letterSpacing: "-0.028em" }],
        h2: ["clamp(30px, 3vw, 40px)", { lineHeight: "1.18", fontWeight: "500", letterSpacing: "-0.018em" }],
        h3: ["26px", { lineHeight: "1.3", fontWeight: "500", letterSpacing: "-0.012em" }],
        h4: ["20px", { lineHeight: "1.4", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.7", fontWeight: "400" }],
        body: ["16px", { lineHeight: "1.65", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.55", fontWeight: "400" }],
        caption: ["12px", { lineHeight: "1.5", fontWeight: "500" }],
        overline: ["11px", { lineHeight: "1.4", fontWeight: "700", letterSpacing: "0.14em" }],
      },
      keyframes: {
        "fade-in": { "0%": { opacity: "0", transform: "translateY(8px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        "slide-in-top": { "0%": { opacity: "0", transform: "translateY(-16px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        float: { "0%, 100%": { transform: "translateY(0) translateX(0)" }, "50%": { transform: "translateY(-18px) translateX(6px)" } },
        "float-slow": { "0%, 100%": { transform: "translateY(0) translateX(0)" }, "50%": { transform: "translateY(-12px) translateX(-8px)" } },
        drift: { "0%, 100%": { transform: "translate3d(0,0,0) rotate(0deg)" }, "33%": { transform: "translate3d(20px,-15px,30px) rotate(2deg)" }, "66%": { transform: "translate3d(-15px,10px,10px) rotate(-1deg)" } },
        trace: { "0%": { strokeDashoffset: "1000" }, "100%": { strokeDashoffset: "0" } },
        shimmer: { "0%": { transform: "translateX(-120%) skewX(-20deg)" }, "100%": { transform: "translateX(220%) skewX(-20deg)" } },
        "breathe-glow": { "0%, 100%": { boxShadow: "0 0 32px rgba(255, 107, 53, 0.30)" }, "50%": { boxShadow: "0 0 56px rgba(255, 107, 53, 0.55)" } },
        "pulse-soft": { "0%, 100%": { opacity: "0.6", transform: "scale(1)" }, "50%": { opacity: "1", transform: "scale(1.04)" } },
        "contour-shift": { "0%": { backgroundPosition: "0 0" }, "100%": { backgroundPosition: "600px 600px" } },
      },
      animation: {
        "fade-in": "fade-in 400ms cubic-bezier(0.16, 1, 0.3, 1)",
        "slide-in-top": "slide-in-top 350ms cubic-bezier(0.16, 1, 0.3, 1)",
        float: "float 7s ease-in-out infinite",
        "float-slow": "float-slow 9s ease-in-out infinite",
        drift: "drift 14s ease-in-out infinite",
        trace: "trace 2.4s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        shimmer: "shimmer 2.5s ease-in-out infinite",
        "breathe-glow": "breathe-glow 3.5s ease-in-out infinite",
        "pulse-soft": "pulse-soft 4s ease-in-out infinite",
        "contour-shift": "contour-shift 60s linear infinite",
      },
      transitionTimingFunction: {
        "out-expo": "cubic-bezier(0.16, 1, 0.3, 1)",
        "in-expo": "cubic-bezier(0.7, 0, 0.84, 0)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};

export default config;
